{{- if .Values.forge.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "forge.fullname" . }}-data
  labels:
    {{- include "forge.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.forge.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  {{- if .Values.forge.persistence.storageClass }}
  storageClassName: {{ .Values.forge.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.forge.persistence.size | quote }}
{{- end }}

