{{- if .Values.forge.gcp.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forge.fullname" . }}-gcp-credentials
  labels:
    {{- include "forge.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ .Values.forge.gcp.credentials | b64enc | quote }}
{{- end }}

